// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: cluster.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FutureQCluster_GetClusterInfo_FullMethodName = "/futureq.FutureQCluster/GetClusterInfo"
	FutureQCluster_JoinCluster_FullMethodName    = "/futureq.FutureQCluster/JoinCluster"
	FutureQCluster_LeaveCluster_FullMethodName   = "/futureq.FutureQCluster/LeaveCluster"
)

// FutureQClusterClient is the client API for FutureQCluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FutureQClusterClient interface {
	// GetClusterInfo returns the current cluster topology. Any node responds.
	// Clients should call this on startup and after any connection failure to
	// discover (or re-discover) the current leader.
	GetClusterInfo(ctx context.Context, in *ClusterInfoRequest, opts ...grpc.CallOption) (*ClusterInfoResponse, error)
	// JoinCluster adds a new node to the cluster. The request may be sent to
	// any existing member and will be forwarded to the leader.
	JoinCluster(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// LeaveCluster removes a node from the cluster gracefully. The departing
	// node must call this on itself (or the operator calls it remotely) before
	// shutting down to ensure a clean Raft config-change.
	LeaveCluster(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
}

type futureQClusterClient struct {
	cc grpc.ClientConnInterface
}

func NewFutureQClusterClient(cc grpc.ClientConnInterface) FutureQClusterClient {
	return &futureQClusterClient{cc}
}

func (c *futureQClusterClient) GetClusterInfo(ctx context.Context, in *ClusterInfoRequest, opts ...grpc.CallOption) (*ClusterInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterInfoResponse)
	err := c.cc.Invoke(ctx, FutureQCluster_GetClusterInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *futureQClusterClient) JoinCluster(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, FutureQCluster_JoinCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *futureQClusterClient) LeaveCluster(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, FutureQCluster_LeaveCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FutureQClusterServer is the server API for FutureQCluster service.
// All implementations must embed UnimplementedFutureQClusterServer
// for forward compatibility.
type FutureQClusterServer interface {
	// GetClusterInfo returns the current cluster topology. Any node responds.
	// Clients should call this on startup and after any connection failure to
	// discover (or re-discover) the current leader.
	GetClusterInfo(context.Context, *ClusterInfoRequest) (*ClusterInfoResponse, error)
	// JoinCluster adds a new node to the cluster. The request may be sent to
	// any existing member and will be forwarded to the leader.
	JoinCluster(context.Context, *JoinRequest) (*JoinResponse, error)
	// LeaveCluster removes a node from the cluster gracefully. The departing
	// node must call this on itself (or the operator calls it remotely) before
	// shutting down to ensure a clean Raft config-change.
	LeaveCluster(context.Context, *LeaveRequest) (*LeaveResponse, error)
	mustEmbedUnimplementedFutureQClusterServer()
}

// UnimplementedFutureQClusterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFutureQClusterServer struct{}

func (UnimplementedFutureQClusterServer) GetClusterInfo(context.Context, *ClusterInfoRequest) (*ClusterInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterInfo not implemented")
}
func (UnimplementedFutureQClusterServer) JoinCluster(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedFutureQClusterServer) LeaveCluster(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveCluster not implemented")
}
func (UnimplementedFutureQClusterServer) mustEmbedUnimplementedFutureQClusterServer() {}
func (UnimplementedFutureQClusterServer) testEmbeddedByValue()                        {}

// UnsafeFutureQClusterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FutureQClusterServer will
// result in compilation errors.
type UnsafeFutureQClusterServer interface {
	mustEmbedUnimplementedFutureQClusterServer()
}

func RegisterFutureQClusterServer(s grpc.ServiceRegistrar, srv FutureQClusterServer) {
	// If the following call panics, it indicates UnimplementedFutureQClusterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FutureQCluster_ServiceDesc, srv)
}

func _FutureQCluster_GetClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FutureQClusterServer).GetClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FutureQCluster_GetClusterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FutureQClusterServer).GetClusterInfo(ctx, req.(*ClusterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FutureQCluster_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FutureQClusterServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FutureQCluster_JoinCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FutureQClusterServer).JoinCluster(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FutureQCluster_LeaveCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FutureQClusterServer).LeaveCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FutureQCluster_LeaveCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FutureQClusterServer).LeaveCluster(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FutureQCluster_ServiceDesc is the grpc.ServiceDesc for FutureQCluster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FutureQCluster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "futureq.FutureQCluster",
	HandlerType: (*FutureQClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterInfo",
			Handler:    _FutureQCluster_GetClusterInfo_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _FutureQCluster_JoinCluster_Handler,
		},
		{
			MethodName: "LeaveCluster",
			Handler:    _FutureQCluster_LeaveCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
