// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: producer.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AckLevel controls how durable a batch publish must be before the broker
// acknowledges it.
type AckLevel int32

const (
	AckLevel_ACK_LEVEL_NO_ACK AckLevel = 0
	// ACK_LEVEL_QUORUM: a majority of replicas have committed the Raft log
	// entry before the broker acknowledges. This is the recommended default
	// for production use.
	AckLevel_ACK_LEVEL_QUORUM AckLevel = 1
)

// Enum value maps for AckLevel.
var (
	AckLevel_name = map[int32]string{
		0: "ACK_LEVEL_NO_ACK",
		1: "ACK_LEVEL_QUORUM",
	}
	AckLevel_value = map[string]int32{
		"ACK_LEVEL_NO_ACK": 0,
		"ACK_LEVEL_QUORUM": 1,
	}
)

func (x AckLevel) Enum() *AckLevel {
	p := new(AckLevel)
	*p = x
	return p
}

func (x AckLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_producer_proto_enumTypes[0].Descriptor()
}

func (AckLevel) Type() protoreflect.EnumType {
	return &file_producer_proto_enumTypes[0]
}

func (x AckLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckLevel.Descriptor instead.
func (AckLevel) EnumDescriptor() ([]byte, []int) {
	return file_producer_proto_rawDescGZIP(), []int{0}
}

// PublishMessage is a single scheduled message inside a PublishBatch.
type PublishMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic identifies the logical channel for this message.
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload is the opaque application data to deliver to consumers.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// delay_ms is the number of milliseconds from the broker's receive time
	// before this message becomes eligible for delivery. Must be >= 0.
	// A value of 0 means "deliver on the next dispatcher tick".
	DelayMs int64 `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	// ttl_ms is the message time-to-live in milliseconds, measured from the
	// broker's receive time. If the message has not been consumed within
	// ttl_ms milliseconds it will be lazily discarded. 0 means no expiry.
	TtlMs         int64 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMessage) Reset() {
	*x = PublishMessage{}
	mi := &file_producer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMessage) ProtoMessage() {}

func (x *PublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_producer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMessage.ProtoReflect.Descriptor instead.
func (*PublishMessage) Descriptor() ([]byte, []int) {
	return file_producer_proto_rawDescGZIP(), []int{0}
}

func (x *PublishMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishMessage) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *PublishMessage) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

// PublishBatch is a single frame sent by the producer on the PublishStream.
// All messages in the batch are written atomically as a single Raft log entry.
type PublishBatch struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*PublishMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// ack_level controls when the broker acknowledges this batch.
	// Defaults to ACK_LEVEL_QUORUM when unspecified.
	AckLevel      AckLevel `protobuf:"varint,2,opt,name=ack_level,json=ackLevel,proto3,enum=futureq.AckLevel" json:"ack_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatch) Reset() {
	*x = PublishBatch{}
	mi := &file_producer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatch) ProtoMessage() {}

func (x *PublishBatch) ProtoReflect() protoreflect.Message {
	mi := &file_producer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatch.ProtoReflect.Descriptor instead.
func (*PublishBatch) Descriptor() ([]byte, []int) {
	return file_producer_proto_rawDescGZIP(), []int{1}
}

func (x *PublishBatch) GetMessages() []*PublishMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PublishBatch) GetAckLevel() AckLevel {
	if x != nil {
		return x.AckLevel
	}
	return AckLevel_ACK_LEVEL_NO_ACK
}

// PublishBatchAck is the broker's response to a PublishBatch frame.
// The whole batch was either successful or failed.
type PublishBatchAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success is true if the message was persisted successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// error_message contains a human-readable description if success is false.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchAck) Reset() {
	*x = PublishBatchAck{}
	mi := &file_producer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchAck) ProtoMessage() {}

func (x *PublishBatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_producer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchAck.ProtoReflect.Descriptor instead.
func (*PublishBatchAck) Descriptor() ([]byte, []int) {
	return file_producer_proto_rawDescGZIP(), []int{2}
}

func (x *PublishBatchAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishBatchAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_producer_proto protoreflect.FileDescriptor

const file_producer_proto_rawDesc = "" +
	"\n" +
	"\x0eproducer.proto\x12\afutureq\"r\n" +
	"\x0ePublishMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x03R\adelayMs\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03R\x05ttlMs\"s\n" +
	"\fPublishBatch\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.futureq.PublishMessageR\bmessages\x12.\n" +
	"\tack_level\x18\x02 \x01(\x0e2\x11.futureq.AckLevelR\backLevel\"P\n" +
	"\x0fPublishBatchAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*6\n" +
	"\bAckLevel\x12\x14\n" +
	"\x10ACK_LEVEL_NO_ACK\x10\x00\x12\x14\n" +
	"\x10ACK_LEVEL_QUORUM\x10\x012W\n" +
	"\x0fFutureQProducer\x12D\n" +
	"\rPublishStream\x12\x15.futureq.PublishBatch\x1a\x18.futureq.PublishBatchAck(\x010\x01B)Z'github.com/futureq-io/protocol/proto/gob\x06proto3"

var (
	file_producer_proto_rawDescOnce sync.Once
	file_producer_proto_rawDescData []byte
)

func file_producer_proto_rawDescGZIP() []byte {
	file_producer_proto_rawDescOnce.Do(func() {
		file_producer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producer_proto_rawDesc), len(file_producer_proto_rawDesc)))
	})
	return file_producer_proto_rawDescData
}

var file_producer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_producer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_producer_proto_goTypes = []any{
	(AckLevel)(0),           // 0: futureq.AckLevel
	(*PublishMessage)(nil),  // 1: futureq.PublishMessage
	(*PublishBatch)(nil),    // 2: futureq.PublishBatch
	(*PublishBatchAck)(nil), // 3: futureq.PublishBatchAck
}
var file_producer_proto_depIdxs = []int32{
	1, // 0: futureq.PublishBatch.messages:type_name -> futureq.PublishMessage
	0, // 1: futureq.PublishBatch.ack_level:type_name -> futureq.AckLevel
	2, // 2: futureq.FutureQProducer.PublishStream:input_type -> futureq.PublishBatch
	3, // 3: futureq.FutureQProducer.PublishStream:output_type -> futureq.PublishBatchAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_producer_proto_init() }
func file_producer_proto_init() {
	if File_producer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producer_proto_rawDesc), len(file_producer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producer_proto_goTypes,
		DependencyIndexes: file_producer_proto_depIdxs,
		EnumInfos:         file_producer_proto_enumTypes,
		MessageInfos:      file_producer_proto_msgTypes,
	}.Build()
	File_producer_proto = out.File
	file_producer_proto_goTypes = nil
	file_producer_proto_depIdxs = nil
}
